Module4 task1
htmlacademy-adaptive/1411729-cat-energy-1 pull request #5
Opened 2024-03-16 13:23 UTC by AleksanrReva

2024-03-17 12:32 UTC, Kartaviy-arteom requested changes
нужно исправить ошибки линтеров (npm run lint)

2024-03-17 12:32 UTC, Kartaviy-arteom commented on source/less/blocks/advantages.less
> +    grid-template-columns: repeat(2, 250px);
тут лучше колонки тоже тянуть grid-template-columns: repeat(2, 1fr)

2024-03-17 12:32 UTC, Kartaviy-arteom commented on source/less/blocks/site-footer.less
> +  margin-bottom: 40px;
изображение внутри должно "закрыввать весь блок"

2024-03-17 12:32 UTC, Kartaviy-arteom commented on source/less/blocks/footer-links.less
> +.footer-links__list  {
будет ломаться футер при переполнениями соц сетями

2024-03-19 07:36 UTC, AleksanrReva commented on source/less/blocks/advantages.less
> +    grid-template-columns: repeat(2, 250px);
![Снимок экрана 2024-03-18 204327](https://github.com/htmlacademy-adaptive/1411729-cat-energy-1/assets/48528980/1a44426b-e3a7-4a11-b010-20477c973957)
У меня так едет вёрстка, что мелочи, но нужно будет тогда шириной ровнять текст, плюс там же нумерация на фоне, тоже потребует отступов. Или ок?

2024-03-22 19:32 UTC, merged